# Generated by Django 4.1.5 on 2023-02-06 01:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pet', '0003_remove_pet_specie_pet_create_date_pet_race_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('create_date', models.CharField(db_column='create_date', max_length=255)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('street', models.CharField(db_column='street', max_length=255, verbose_name='Rua')),
                ('city', models.CharField(db_column='city', max_length=255, verbose_name='Cidade')),
                ('complement', models.CharField(db_column='complement', max_length=255, verbose_name='Complemento')),
                ('state', models.CharField(db_column='state', max_length=255, verbose_name='Estado')),
                ('zip_code', models.CharField(db_column='zip_code', max_length=255, verbose_name='CEP')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LocalData',
            fields=[
                ('create_date', models.CharField(db_column='create_date', max_length=255)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='local.address', verbose_name='Endereço')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet.pet', verbose_name='Pets')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manager', to=settings.AUTH_USER_MODEL, verbose_name='Usuário associado')),
            ],
        ),
    ]
