# Generated by Django 4.1.5 on 2023-03-26 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='localdata',
            name='cnpj',
            field=models.IntegerField(default=15156156, verbose_name='CPF'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='localdata',
            name='email',
            field=models.EmailField(default='teste@teste.com', max_length=254, verbose_name='Email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='localdata',
            name='name',
            field=models.CharField(db_column='state', default='name', max_length=255, verbose_name='Nome'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='localdata',
            name='telephone',
            field=models.CharField(default=21987945953, max_length=11, verbose_name='Telefone'),
            preserve_default=False,
        ),
    ]
