version: '2.2'

services:

  web:
    build: .
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./padpet_back:/padpet_back
    ports:
      - "8000:8000"
    depends_on:
      - db
    links:
      - db:db
    networks:
      - djangonetwork

  web_front:
    build: ./padpet-front
    ports:
      - "3000:3000"
    volumes:
      - ./padpet-front:/padpet-front

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    networks:
      - djangonetwork
volumes:
  postgres_data:
networks:
  djangonetwork:
    driver: bridge