version: '2.2'

services:

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:80"
    networks:
      - djangonetwork

  web:
    build: .
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./padpet_back:/padpet_back
    ports:
      - "8000:8000"
    depends_on:
      - db
    links:
      - db:db
    networks:
      - djangonetwork

  web_front:
    build: ./padpet-front
    ports:
      - "3000:3000"
    volumes:
      - ./padpet-front:/padpet-front
  pg-padpet:
    restart: always
    image: dpage/pgadmin4
    container_name: pg-padpet
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com.br
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - db

    networks:
    - djangonetwork
    # volumes:
      # - pgadmin_wdata:/var/lib/storage
      # - ./pgadmin_storage:/var/lib/pgadmin/storage

volumes:
  postgres_data:
networks:
  djangonetwork:
    driver: bridge