# Generated by Django 4.1.5 on 2023-03-26 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfos',
            old_name='tel',
            new_name='telephone',
        ),
    ]
