# Generated by Django 4.1.5 on 2023-02-05 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=255)),
            ],
            options={
                'db_table': 'race',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Specie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=255)),
                ('race', models.ManyToManyField(null=True, related_name='race_set', to='pet.race', verbose_name='race')),
            ],
            options={
                'db_table': 'specie',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=255)),
                ('specie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='specie_set', to='pet.specie', verbose_name='Espécie')),
            ],
            options={
                'db_table': 'pet',
                'managed': True,
            },
        ),
    ]
