# Generated by Django 4.1.7 on 2023-03-28 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0003_remove_pet_specie_pet_create_date_pet_race_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='specie',
            field=models.CharField(db_column='specie', default='dog', max_length=255),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='pet',
            name='race',
        ),
        migrations.AddField(
            model_name='pet',
            name='race',
            field=models.CharField(db_column='race', default='york shire', max_length=255),
            preserve_default=False,
        ),
    ]
