# Generated by Django 4.1.7 on 2023-03-28 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0004_pet_specie_remove_pet_race_pet_race'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='age',
            field=models.CharField(db_column='age', default='2', max_length=255),
            preserve_default=False,
        ),
    ]
