# Generated by Django 4.1.7 on 2023-04-09 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0006_remove_pet_race_remove_pet_specie'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='race',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pet_race_set', to='pet.race', verbose_name='race'),
        ),
        migrations.AddField(
            model_name='pet',
            name='specie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='specie', to='pet.specie', verbose_name='specie'),
        ),
    ]
