# Generated by Django 4.1.7 on 2023-04-11 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0007_pet_race_pet_specie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specie',
            name='race',
        ),
        migrations.AddField(
            model_name='race',
            name='specie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='specie_race_set', to='pet.specie', verbose_name='specie'),
        ),
    ]
