# Generated by Django 4.1.4 on 2022-12-26 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teste',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='nome', max_length=255)),
            ],
            options={
                'db_table': 'teste',
                'managed': True,
            },
        ),
    ]
