# Generated by Django 4.1.5 on 2023-01-29 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=255)),
            ],
            options={
                'db_table': 'teste',
                'managed': True,
            },
        ),
    ]
