# Generated by Django 4.1.5 on 2023-01-29 22:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfos',
            fields=[
                ('creation_date', models.DateTimeField(auto_now_add=True, help_text='Data quando a ANP ou o Declarante criaram este item', verbose_name='Data da Criação')),
                ('modification_date', models.DateTimeField(auto_now=True, help_text='Data quando a ANP ou o Declarante alterou este item', verbose_name='Data da Atualização')),
                ('annotation', models.CharField(blank=True, help_text='Anotação/Justificativa sobre a atualização no item', max_length=500, null=True, verbose_name='Justificativa')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('sent', 'Submetido - Em avaliação'), ('waiting_adjustment', 'Em exigência - Aguardando Retificação'), ('waiting_review', 'Em exigência - Aguardando Reavaliação'), ('waiting_incorporation', 'Aprovado - Aguardando Incorporação'), ('waiting_manual_incorporation', 'Aprovado - Falha na incorporação / Aguardando incorporação manual'), ('consumed', 'Implementado / Incorporado')], default='draft', max_length=40, verbose_name='Estado do Objeto')),
                ('declaration_type', models.CharField(choices=[('new_sample', 'Nova amostra'), ('reentry', 'Reentrada'), ('transference', 'Transferência de Depositária'), ('change_deposit', 'Mudança de depósito'), ('unavailable_analysis', 'Indisponível por Análise Nacional (uso próprio)'), ('unavailable_external_analysis', 'Indisponível por Análise Nacional de terceiros'), ('destructive_analysis', 'Análise Destrutiva'), ('unavailable_insufficient_amount', 'Indisponível por Amostra insuficiente')], default='new_sample', help_text='Tipo de declaração', max_length=100, verbose_name='Tipo de declaração')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=255)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('next', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='main.userinfos', verbose_name='Próxima fase')),
                ('previous', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='main.userinfos', verbose_name='Fase Anterior')),
                ('root', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='main.userinfos', verbose_name='Original')),
            ],
            options={
                'db_table': 'user_info',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='WrongField',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('verbose_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'anp_daa_wrong_field',
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='userinfos',
            name='wrong_fields',
            field=models.ManyToManyField(blank=True, to='main.wrongfield', verbose_name='Campos com erros'),
        ),
    ]
