# Generated by Django 4.1.5 on 2023-02-05 20:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_userinfos_wrongfield_delete_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegitryBaseModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_date', models.CharField(db_column='name', max_length=255)),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'registry_info',
                'managed': True,
            },
        ),
    ]
