# Generated by Django 4.1.5 on 2023-02-05 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_regitrybasemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regitrybasemodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
