# Generated by Django 4.1.5 on 2023-02-05 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_regitrybasemodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regitrybasemodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
