# Generated by Django 4.1.5 on 2023-02-06 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_regitrybasemodel_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegitryBaseModel',
        ),
    ]
